// Curated lists of IGDB genres and themes for dropdown filters.
// These match the canonical names used in the IGDB API.

export const IGDB_GENRES = [
    "Adventure",
    "Arcade",
    "Card & Board Game",
    "Fighting",
    "Hack and Slash/Beat 'em up",
    "Indie",
    "MOBA",
    "Music",
    "Pinball",
    "Platform",
    "Point-and-click",
    "Puzzle",
    "Quiz/Trivia",
    "Racing",
    "Real Time Strategy (RTS)",
    "Role-playing (RPG)",
    "Shooter",
    "Simulator",
    "Sport",
    "Strategy",
    "Tactical",
    "Turn-based strategy (TBS)",
    "Visual Novel",
];

export const IGDB_THEMES = [
    "Action",
    "Business",
    "Comedy",
    "Drama",
    "Educational",
    "Erotic",
    "Fantasy",
    "Historical",
    "Horror",
    "Kids",
    "Mystery",
    "Non-fiction",
    "Open world",
    "Party",
    "Romance",
    "Sandbox",
    "Science fiction",
    "Stealth",
    "Survival",
    "Thriller",
    "Warfare",
];
